# Generated by Django 4.0.2 on 2024-02-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_alter_customuser_groups_and_more'),
        ('Auth', '0007_testimonials'),
    ]

    operations = [
    ]
