# Generated by Django 5.0.1 on 2024-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_merge_20240214_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isAdmin',
            field=models.BooleanField(default=True),
        ),
    ]
