# Generated by Django 5.0.1 on 2024-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_customuser_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
