# Generated by Django 5.0.1 on 2024-02-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_alter_customuser_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isAdmin',
        ),
    ]
