# Generated by Django 5.0.1 on 2024-02-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_rename_customuser_authuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthUser',
            new_name='CustomUser',
        ),
    ]
