# Generated by Django 5.0.1 on 2024-03-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0018_customuser_is_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeraccount",
            name="number",
            field=models.CharField(default=54987897, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
