# Generated by Django 5.0.1 on 2024-03-17 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0019_brokeraccount_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brokeraccount",
            name="number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_agent",
        ),
    ]
