# Generated by Django 5.0.1 on 2024-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0020_remove_brokeraccount_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeraccount",
            name="number",
            field=models.CharField(default=123, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
    ]
