# Generated by Django 5.0.1 on 2024-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0021_brokeraccount_number_customuser_is_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="agentId",
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
