# Generated by Django 5.0.1 on 2024-03-19 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0022_customuser_agentid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="agentId",
        ),
    ]
