# Generated by Django 5.0.1 on 2024-03-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0023_remove_customuser_agentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="agentId",
            field=models.IntegerField(default=0),
        ),
    ]
