# Generated by Django 5.0.1 on 2024-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0024_customuser_agentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="latitude",
            field=models.FloatField(default=27.707),
        ),
        migrations.AddField(
            model_name="properties",
            name="longitude",
            field=models.FloatField(default=885.34238),
        ),
    ]
