# Generated by Django 5.0.1 on 2024-03-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0026_remove_review_property_review_broker_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="broker_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Auth.brokeraccount"
            ),
        ),
    ]
