# Generated by Django 5.0.1 on 2024-03-25 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0027_alter_review_broker_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="broker_id",
            new_name="broker",
        ),
    ]
