# Generated by Django 4.0.2 on 2024-04-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0029_properties_is_rent'),
        ('Auth', '0030_customuser_facebooklink_customuser_instagramlink_and_more'),
    ]

    operations = [
    ]
