# Generated by Django 5.0.1 on 2024-04-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0031_merge_20240428_1013"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="properties",
            name="is_rent",
        ),
        migrations.AddField(
            model_name="properties",
            name="type",
            field=models.CharField(default="Sale", max_length=30),
        ),
    ]
