# Generated by Django 5.0.1 on 2024-05-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0033_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="isPaid",
            field=models.BooleanField(default=False),
        ),
    ]
