# Generated by Django 5.0.1 on 2024-05-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0034_booking_ispaid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellingProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="/static/images/img_1.jpg", upload_to="media/"
                    ),
                ),
                (
                    "imageTwo",
                    models.ImageField(
                        default="/static/images/img_1.jpg", upload_to="media/"
                    ),
                ),
                (
                    "imageThree",
                    models.ImageField(
                        default="/static/images/img_1.jpg", upload_to="media/"
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=50)),
                ("beds", models.CharField(max_length=10)),
                ("baths", models.CharField(max_length=10)),
                ("price", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=1000)),
                ("latitude", models.FloatField(default=27.707)),
                ("longitude", models.FloatField(default=85.34238)),
                ("type", models.CharField(default="Sale", max_length=30)),
            ],
        ),
    ]
