# Generated by Django 5.0.6 on 2024-05-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0035_sellingproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='txnId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
