# Generated by Django 5.0.6 on 2024-05-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0036_payment_txnid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokeraccount',
            name='linkedInLink',
        ),
        migrations.RemoveField(
            model_name='brokeraccount',
            name='twitterLink',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedInLink',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitterLink',
        ),
    ]
