# Generated by Django 5.0.6 on 2024-05-28 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0038_alter_properties_broker_alter_review_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingproperties',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
